### ISSUE TITLE
Moving table rows with percentage-based style width?

### ISSUE THREAD

**Issue by johnridesabike** [tajo/react-movable#10]
I’ve been trying to figure out how to correctly render a draggable table where the rows & data cells use a percentage-based width. The problem I encounter is that when a row is dragging (`isDragged` is true) the data cells collapse to fit the width of their content. I’ve mostly followed the table example from here, but changed the styles and data to match my own app. My `isDragged` row is wrapped in a `<table>` element in the `renderItem` function, with the same styles as the regular `<table>` in the `renderList`.

It seems like no matter how I style the table, the `isDragged` row will always collapse unless I use pixel units for its width.

I tried following some of the advice from react-beautiful-dnd ([here](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/tables.md)) but it doesn’t seem to apply to react-movable (or I’m just doing it incorrectly).

**Comment by tajo** [comment]
I've added a new `beforeDrag` API and an example: https://github.com/tajo/react-movable/pull/11

The dragged row is rendered into a new `table` at the end of the page (through the portal), so it doesn't know anything about other row dimensions. So you need to measure the cell widths before the dragging actually starts (thus the new API) and set them to the dragged / portaled row.

**Comment by tajo** [comment]
> percentage-based style width

If you set `width: '20%'` to a cell it's still fixed width and that works even today. So you actually meant not setting the width upfront, right?

**Comment by johnridesabike** [comment]
Here’s an example of what I was trying to do: https://codesandbox.io/s/k950nv8zyr?fontsize=14

I copied the current example, but changed the table width to 100% and set the td widths to 25%. When you click to drag a row, you can see it collapse. It’s more obvious on the rows with less content in the table cells.

**Comment by tajo** [comment]
I see. My PR would solve this use-case too. Since the dragged item (row) it taken out of the DOM, it doesn't know what `100%` means, so you need to measure it in `beforeDrag` and then set it. Can you test it? Does it make sense?

**Comment by johnridesabike** [comment]
I think so! I just played with my example a bit with the updated code, and it seems to behave as expected for my scenario. You can see here: https://codesandbox.io/s/k950nv8zyr?fontsize=14&module=%2Fsrc%2Ftable-auto.jsx

**Comment by tajo** [comment]
That just works even without the change. You can't really test my PR through CodeSandbox.

**Comment by johnridesabike** [comment]
Ah, I see. I can’t test the PR right now, but the code seems to make sense to me. Basically, you would use the new `beforeDrag` prop in combination with `window.getComputedStyle` to keep the table cells the appropriate width while dragging? I’ll update if I can do any tests.

**Comment by tajo** [comment]
The `beforeDrag` API has been added as `v2.1.1`
