### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by iaculch** [tajo/react-movable#100]
It appears the library does not take into account the React Fibre architecture of React 18, the only way I have been able to use the library without flashing issues and other errors is to wrap any state updates in `flushSync`.

Are there any plans to make this library React 18 compatible?

**Comment by tajo** [comment]
is there some reproduction for this? afaik, we use this with React v18 already

**Comment by iaculch** [comment]
I'm sorry but it's been a few months now since we moved from `react-movable` to `dnd-kit`, at the time I had debugged this flashing issue and found myself in `react-movable` internals, it confused me that another older project which was on React 17 was working fine for essentially the same code.

If React 18 support is not an issue for others, you may be able to close this issue.
