### ISSUE TITLE
JSX element class does not support attributes because it does not have a 'props' property.ts(2607)

### ISSUE THREAD

**Issue by Praskand** [tajo/react-movable#112]
page.tsx
![365340454-bab70b5f-703f-49f5-aeff-24b563bf073f](https://github.com/user-attachments/assets/85478fc8-370a-4cfd-8497-d1f01855959f)
error appears on hover.

**Comment by muratsu** [comment]
This is likely to be a resolution issue that's not related to the lib. Are you using a mono repo? If so can you share a small codebox/stackblitz
