### ISSUE TITLE
Errors if an item is being dragged when the parent component is onmounted

### ISSUE THREAD

**Issue by badtant** [tajo/react-movable#12]
utils.js:32 Uncaught TypeError: Cannot read property 'style' of null
    at Object.transformItem (utils.js:32)
    at List._this.onMove (List.js:165)
    at List._this.onMouseMove (List.js:150)
    at utils.js:80

-----------

No items found in the List container. Did you forget to pass & spread the `props` param in renderList?

-----------

react-dom.development.js:506 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in List (created by Sort)
    in div (created by Sort)
    in Sort (created by ConnectFunction)
    in ConnectFunction (created by ActiveElement)

**Comment by tajo** [comment]
Can you provide an example that reproduces this error? Ideally with as a CodeSandbox.

**Comment by badtant** [comment]
Here's a Sandbox: https://codesandbox.io/s/6zmv1kpvn3

The component containing List will unmount after 5 seconds. Drag one of the items when the component unmounts.

**Comment by tajo** [comment]
That's a strange use-case. Why would you unmount the component when user is interacting with it. Also, it throws just warnings not errors.

**Comment by badtant** [comment]
In my case the user has a limited amount of time to answer a question. The question is answered by ordering some items. Not too strange :)

**Comment by tajo** [comment]
Well if the warning bothers you, you can come up with a different interaction. Like keeping the List mounted but ignoring the `onChange` and giving user some explanatory message which is arguably better than just making the whole thing to disappear.

**Comment by badtant** [comment]
the sandbox doesn't contain all the UI the user will see, it's just to reproduce the problem
