### ISSUE TITLE
cant use "rest of item" to scroll when i have data-movable-handle

### ISSUE THREAD

**Issue by badtant** [tajo/react-movable#13]
So, I have items with a drag handle (data-movable-handle).
When touching and dragging on the rest of the item I expect the page to scroll. It doesn't.

**Comment by arturbani** [comment]
Hi! This is happening because of  the `touchAction: none` on `baseStyle` applied to the list. Probably this will fix #30 too. I'm having this problem and figuring out a solution, i'll open an PR if can work it out.

Until then, do you have any ideas @tajo ?

**Comment by IcebergRage** [comment]
Hello,
I still have the problem with the 2.5.0
Did you find a solution to fix it ?

**Comment by arturbani** [comment]
Hi @IcebergRage , check this PR https://github.com/tajo/react-movable/pull/39 , it fixes this bug. I closed it because another commit was added on the PR by accident and I forgot to fix it 😅

**Comment by arturbani** [comment]
@IcebergRage , I've opened a PR with the fix on #46  =)

**Comment by IcebergRage** [comment]
Thank you ! It works :)
