### ISSUE TITLE
Cannot be used with HOCed components

### ISSUE THREAD

**Issue by rassie** [tajo/react-movable#14]
I'm trying to use `react-movable` with Material UI (e.g. [`List` component](https://material-ui.com/demos/lists/)) and fail at that. The main problem seems to be that Material UI wraps its components in a HOC for styling, which does not have a `children` property, which `react-movable` expects to exist. Replacing a component with HTML-like components like `<ul>` works more or less as expected, however can't be a solution in a component world.

**Comment by tajo** [comment]
The problem is that material-ui is not correctly forwarding `refs`. However, it has an alternative API called `innerRef` (https://material-ui.com/customization/css-in-js/#withstyles-styles-options-higher-order-component). You need to pass the ref into it.

**Comment by tajo** [comment]
v4 will start forwarding refs https://next.material-ui.com/guides/migration-v3/#core

**Comment by rassie** [comment]
Thanks, I'll look into it!

**Comment by rassie** [comment]
For the history: I haven't been able to use `innerRef` for this, but with `RootRef` it's working fine. It looks like this (`List` is Material-UI's `List`):
```
<RootRef rootRef={props.ref}>
    <List {...props}>{children}</List>
</RootRef>
```
