### ISSUE TITLE
Expose more events

### ISSUE THREAD

**Issue by danbriggs5** [tajo/react-movable#20]
I appreciate your focus on minimalism and sticking to just the essentials! It's a great library. I'm wondering if any of the following additions would make the cut to be added?

1. `onDragEnd` event that fires regardless of whether a change occurs or not. I'm using `beforeDrag` to track when dragging is actually occurring and customizing the UI. But I need custom logic to determine when it stops.
2. Send the `clientX` and `clientY` positions as part of the `beforeDrag` event.
3. `onMove` event that includes `clientX` and `clientY`. I think 2&3 would allow for greater customization without adding any bulk to the library. Personally, I'd like to use 2&3 to change the cursor to a grabber only once the item has been dragged > 5px. Why? Because it's clickable until it's been dragged a few pixels (similar to Trello drag and drop).

**Comment by tajo** [comment]
I am open to this. Agreed that this doesn't add any bulk to the library; however, it increases the API surface so not taking this lightly. 

1. Would it be called after or before `onChange`? Why?  Maybe it should be called `afterDrag` to pair with `beforeDrag`?
2. onChange now returns `targetRect` (superset of `clientX` and `clientY`), so ideally we could return the same thing in all these events.
3. That's a good use-case that I left out initially, so I'm fine with adding that. Would `onMove` interact with keyboard shortcuts?

Willing to open a PR, update the documentation and add some tests? :)

**Comment by EternallLight** [comment]
Hi @tajo 
I've watched your talk at React Advanced London and thereby found this project. You've done very cool job! Mind if I take this issue?

**Comment by tajo** [comment]
@EternallLight sure, thanks!

**Comment by jpca999** [comment]
Any update on this ?

**Comment by tajo** [comment]
There doesn't seem to be much traction / strong need. Closing for now. Happy to discuss additions later if people have good use-cases.
