### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by konstantinn** [tajo/react-movable#22]
Hello. First of all thanks for great library, simple and clean. 

Readme states that IE 11 is supported but I've encountered small issue with it. 
Here https://github.com/tajo/react-movable/blob/v2.2.0/src/List.tsx#L132
`findIndex` method is used which seems to be not fully supported by IE 
https://caniuse.com/#search=findIndex

At least I've got 
<img width="698" alt="Screen Shot 2019-08-20 at 2 02 52 PM" src="https://user-images.githubusercontent.com/5270546/63342050-3d520c80-c353-11e9-8d82-01f46871ac67.png">
and had to add this library to webpack config.

**Comment by tajo** [comment]
You could fix this by using babel/polyfill or core-js. Also, if this is the only problem, I am happy to accept PR replacing this method by something compatible.
