### ISSUE TITLE
The onKeyDown handler eats the event of any nested Textarea.onChange handlers.

### ISSUE THREAD

**Issue by shenders13** [tajo/react-movable#23]
Hi React-Movable folks,

Just a heads up - a text area component that was deeply nested inside a `renderItem` wasn't receiving an `onChange` event when the text area was updated.

The fix was to remove the `onKeyDown` props that was being applied way up the component tree.

May be worth adding this to the docs as it was super tricky to debug.

Thanks for your awesome library.

Best wishes,

Sam

**Comment by tajo** [comment]
Fixed and released.

**Comment by andrewringler** [comment]
This seems to still be an issue. I forked the sandbox from the README and added the InteractiveItems example from the repo. I can edit the input form but I cannot types spaces into the input field, see sandbox here:

<https://codesandbox.io/s/basic-react-movable-forked-01ebo>

Additionally, while testing locally I am seeing this issue even when using the `data-movable-handle`. I had thought that if I had a handle somewhere in my item than any other element would not have input events captured. It might be worth adding something like a `data-movable-interactive` attribute that users can add to their own interactive elements to signify that they don't want any react-movable events captured on them.

**Comment by tajo** [comment]
@andrewringler It got fixed in `v2.4`, the codesandbox example was using `v2.0`. I've updated that. Thanks.

**Comment by andrewringler** [comment]
Aaah. Thanks.
