### ISSUE TITLE
Add support for Grid mode

### ISSUE THREAD

**Issue by felixmosh** [tajo/react-movable#29]
Hi,

First of all thank you for this great lib 🙏🏼

Is this lib can support Grid sorting?

![image](https://user-images.githubusercontent.com/9304194/68541467-948ed880-03a8-11ea-8e4e-1f31c13c6352.png)

**Comment by tajo** [comment]
Hey, unfortunately not, the library is focused only on the vertical sorting. 

I wanted to link you to an [alternative](https://clauderic.github.io/react-sortable-hoc/#/basic-configuration/grid?_k=d7wnc8) but it seems your screenshot is from there so you are aware.

**Comment by felixmosh** [comment]
Will you approve PR for this? 
currently I'm using hoc, and it has weird bugs with layouts baed on RTL langs.

**Comment by tajo** [comment]
Hm, I think it would be a lot of new code (increasing the size significantly) for something that's seems as a very different use-case. It might make sense to ship it as a separate library and maybe reuse some parts of react-movable?

**Comment by felixmosh** [comment]
Sounds reasonable, thanx
