### ISSUE TITLE
Ghost element changing dragged component CSS

### ISSUE THREAD

**Issue by arturbani** [tajo/react-movable#37]
Hi! 
I saw that `ghostStyle` has `display: block`. This changes the dragged element CSS if it is using, for example, `display: flex` (my case).

Any thoughts on maybe making this an optional prop? I'm happy to contribute if it makes sense for the lib!

**Comment by tajo** [comment]
> Any thoughts on maybe making this an optional prop? 

Yea, it's probably not necessary.  

> I'm happy to contribute if it makes sense for the lib!

Sure, thanks!
