### ISSUE TITLE
When used in modal, the item is shown in the back.

### ISSUE THREAD

**Issue by monthlysongmi** [tajo/react-movable#59]
<img width="458" alt="error" src="https://user-images.githubusercontent.com/57933306/98902086-5dda2980-24f8-11eb-97fb-09a888720671.png">

Hello

I'm using it with gratitude.
There's an issue, so I leave a message.
When used in modal, the item is shown in the back.

I used this code. 
https://github.com/tajo/react-movable/blob/master/examples/Basic.tsx

I'd appreciate it if you could help me with how to revise it.

Have a good day. @tajo @dumbmatter @lindskogen @cbschuld @moroshko

**Comment by tajo** [comment]
You can render dragged item into custom [container](https://github.com/tajo/react-movable#container) or change `zIndex`. It depends how your modal / layering is implemented.

**Comment by monthlysongmi** [comment]
> You can render dragged item into custom [container](https://github.com/tajo/react-movable#container) or change `zIndex`. It depends how your modal / layering is implemented.

Thank you for your answers.
For your information, I'll test it out.
