### ISSUE TITLE
createPortal issue while using react-movable within a modal/overlay

### ISSUE THREAD

**Issue by rohit1901** [tajo/react-movable#65]
When an element of the list (li), within an overlay(modal), is dragged, it is not visible. Upon debugging, I found out, that the ReactDOM.createPortal is appending the ghostElement in the body instead of the parent (modal).

Is there anyone who has faced this problem?

**Comment by tajo** [comment]
You can specify a custom [container](https://github.com/tajo/react-movable#container) for the dragged element.

**Comment by rohit1901** [comment]
Hi,
So, it doesn't seen to work.
My code looks like this:


`import {Button, H2, IconLink, InputCheckbox, Layer, Paragraph} from "@lsg/components";
import {interaction___more02, interaction___trash} from "@lsg/icons";
import {arrayMove, List} from 'components/Custom/react-drag';
import {DropDownButton} from "components/DropDownButton";
import {useGPPTranslation as useTranslation} from "containers/App/Language";
import {DropdownButton} from "containers/TransactionsUpload/DropdownButton";
import React from "react";
import {useDispatch, useSelector} from "react-redux";
import {AppState} from "redux-store";
import {Separator, Spacer} from "styled";
import styled from "styled-components";

type AccountSelectionOverlayProps = {
  openAccountSelectionOverlay: boolean;
  setOpenAccountSelectionOverlay: Function;
};

export const AccountSelectionOverlay: React.FC<AccountSelectionOverlayProps> = ({
                                                                                  openAccountSelectionOverlay,
                                                                                  setOpenAccountSelectionOverlay
                                                                                }) => {
  const wrapper = React.useRef<HTMLDivElement>(null);
  const [container, setContainer] = React.useState<Element | null>(null);

  React.useEffect(() => {
    setContainer(wrapper.current);
  }, [wrapper.current]);


  const {t} = useTranslation();
  //const {items} = useSelector((state: AppState) => state.accountOverview);
  const [items, setItems] = React.useState(['1. Lorem ipsum dolor sit amet. ',
    '2. Lorem ipsum dolor sit amet. ',
    '3. Lorem ipsum dolor sit amet. ',
    '1. Lorem ipsum dolor sit amet. ',
    '2. Lorem ipsum dolor sit amet. ',
    '3. Lorem ipsum dolor sit amet. ',
    '1. Lorem ipsum dolor sit amet. ',
    '2. Lorem ipsum dolor sit amet. ',
    '3. Lorem ipsum dolor sit amet. ',
    '1. Lorem ipsum dolor sit amet. ',
    '2. Lorem ipsum dolor sit amet. ',
    '3. Lorem ipsum dolor sit amet. ',
    '1. Lorem ipsum dolor sit amet. ',
    '2. Lorem ipsum dolor sit amet. ',
    '3. Lorem ipsum dolor sit amet. ',
    '1. Lorem ipsum dolor sit amet. ',
    '2. Lorem ipsum dolor sit amet. ',
    '3. Lorem ipsum dolor sit amet. ',
    '1. Lorem ipsum dolor sit amet. ',
    '2. Lorem ipsum dolor sit amet. ',
    '3. Lorem ipsum dolor sit amet. ',
    '1. Lorem ipsum dolor sit amet. ',
    '2. Lorem ipsum dolor sit amet. ',
    '3. Lorem ipsum dolor sit amet. ',
    '1. Lorem ipsum dolor sit amet. ',
    '2. Lorem ipsum dolor sit amet. ',
    '3. Lorem ipsum dolor sit amet. ',
    '1. Lorem ipsum dolor sit amet. ',
    '2. Lorem ipsum dolor sit amet. ',
    '3. Lorem ipsum dolor sit amet. ',
    '1. Lorem ipsum dolor sit amet. ',
    '2. Lorem ipsum dolor sit amet. ',
    '3. Lorem ipsum dolor sit amet. ',
    '1. Lorem ipsum dolor sit amet. ',
    '2. Lorem ipsum dolor sit amet. ',
    '3. Lorem ipsum dolor sit amet. ',
    '1. Lorem ipsum dolor sit amet. ',
    '2. Lorem ipsum dolor sit amet. ',
    '3. Lorem ipsum dolor sit amet. ',
    '1. Lorem ipsum dolor sit amet. ',
    '2. Lorem ipsum dolor sit amet. ',
    '3. Lorem ipsum dolor sit amet. ',
    '1. Lorem ipsum dolor sit amet. ',
    '2. Lorem ipsum dolor sit amet. ',
    '3. Lorem ipsum dolor sit amet. ',
    '1. Lorem ipsum dolor sit amet. ',
    '2. Lorem ipsum dolor sit amet. ',
    '3. Lorem ipsum dolor sit amet. ',
    '1. Lorem ipsum dolor sit amet. ',
    '2. Lorem ipsum dolor sit amet. ',
    '3. Lorem ipsum dolor sit amet. ']);

  const dispatch = useDispatch();
  const {selectedAccount} = useSelector((state: AppState) => state.accountOverview);

  const handleSubmit = (value?: string) => {
    /*const val = selectedAccount!.accountIdentification;
    if (_.isEmpty(val) || value!.length > 24) return;
    else dispatch(onSaveAccountIdentification(selectedAccount));*/
  };

  return (
    <Layer
        id={"account-selection-layer"}
        htmlAttrs={{role: "Account Selection layer"}}
        open={openAccountSelectionOverlay}
        onCloseClick={() => {
          setOpenAccountSelectionOverlay(false);
        }}
        closeLinkLabel={t("button.zurueck")}
        layout={Layer.Layout!.FULL}
      >
        <Spacer top={6} bottom={6} left={8} right={8}>
          <H2>{t("label.kontobezeichnung")} {t("label.aendern")}</H2>
          <Button id="saveAccountSelection" onClick={() => handleSubmit()}>
            {t("Speichern")}
          </Button>
        </Spacer>
        <LayerContainer>
          <Spacer top={2} bottom={2}>
            <div
              ref={wrapper}
              style={{
                //maxWidth: '300px',
                margin: '0px auto',
                //backgroundColor: '#F7F7F7',
                padding: '3em'
              }}
            >
              <List
                values={items}
                onChange={({oldIndex, newIndex}) => {
                  setItems(arrayMove(items, oldIndex, newIndex));
                  console.log(oldIndex, newIndex);
                }}
                renderList={({children, props, isDragged}) => <ul {...props}>{children}</ul>}
                renderItem={({value, props, isDragged, isSelected}) => <li {...props}
                                                                           style={{
                                                                             ...props.style,
                                                                             listStyleType: 'none',
                                                                             cursor: isDragged ? 'grabbing' : 'grab'
                                                                           }}>
                  <CheckboxContainer>
                    <Spacer top={3}>
                      <IconLink icon={interaction___trash} look={IconLink?.Looks?.NO_TEXT}/>
                    </Spacer>
                    <InputCheckboxContainer>
                      <Spacer left={4}>
                        <InputCheckbox value={false} onChange={(val) => console.log("clicked")}/>
                      </Spacer>
                    </InputCheckboxContainer>
                    <div>
                      <Spacer top={2} left={12}>
                        {value}
                        <Paragraph size={Paragraph.Sizes.HELPER}>sub label</Paragraph>
                      </Spacer>

                    </div>
                    <span style={{marginLeft: "auto"}}>
                      <DropdownButtonContainer>
                        <DropDownButton
                          minWidth={310}
                          items={[
                            {label: t("Anzeigeberechtigungen verwalten"), onClick: () => console.log()},
                            {
                              label: t("Alle Kontoauszüge anzeigen"),
                              onClick: () => console.log()
                            },
                            {label: t("Aktuellen Auszug drucken (PDF)"), onClick: () => console.log()},
                            {label: t("Aktuellen Auszug exportieren"), onClick: () => console.log()},
                            {label: t("Aktuellen Auszug öffnen"), onClick: () => console.log()},
                            {label: t("Kontobezeichnung ändern"), onClick: () => console.log()},
                            {label: t("Kontodetails anzeigen"), onClick: () => console.log()}
                          ]}
                          icon={interaction___more02}
                        />
                      </DropdownButtonContainer>
                    </span>


                  </CheckboxContainer>
                  <Separator/>
                </li>}
              />
            </div>


          </Spacer>
        </LayerContainer>

      </Layer>
  );
};

const AccountSelectionOverlayContainer = styled.div`
  position: inherit;
`;
const LayerContainer = styled.div`
  position: inherit;
`;

export const CloseIconContainer = styled.div`
  position: fixed;
  cursor: pointer;
  z-index: 10000000;
  top: 24px;
  right: 24px;
  display: ${({show}: { show: boolean }) => (show ? "block" : "none")};
`;

export const DropdownButtonContainer = styled.div`
  display: block;
  margin-top: 16px;
`;

const InputCheckboxContainer = styled.div`
  float: left;
`;
const CheckboxContainer = styled.div`
  display: flex;
  margin-top: 10px;
  margin-bottom: 10px;
`;
`
