### ISSUE TITLE
Warning "No items found in the List container" after unmounting

### ISSUE THREAD

**Issue by mdrobny** [tajo/react-movable#73]
Hi!

I would like to report that there seems to be a problem with proper cleanup after `List` component is unmounted

It always logs a warning:
`No items found in the List container. Did you forget to pass & spread the `props` param in renderList?` 
and it can't be fixed as far I can see (I do of course pass & spread `props` param).

It's very easy to reproduce in the demo page of this library 😕  😅 

Steps to reproduce:
- go to https://react-movable.netlify.app/?story=list--basic 
- sort 1 item
- click on the link to the next example eg. https://react-movable.netlify.app/?story=list--custom-component 
- the warning is logged. Every time you navigate to another example

In my application React logs a big warning also
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    at List (webpack://<app name>/./node_modules/react-movable/lib/List.js?:54:28)
```

In my application it's a normal use case to unmount the `List` and then mount new one because I have tabs menu.

I am not familiar enough with source code to find the cause at the moment but maybe @tajo you are able to look at it?

**Comment by bryan-hunter** [comment]
@mdrobny ran into same issue which causes a memory leak.

Just need to add `window.clearTimeout(this.dropTimeout);`

to the componentWillUnmount, I believe - on this line:

https://github.com/tajo/react-movable/blob/master/src/List.tsx#L72
