### ISSUE TITLE
index for renderItem is undefined while moving

### ISSUE THREAD

**Issue by badtant** [tajo/react-movable#8]
Is this a bug or intentional?

Thanks

**Comment by tajo** [comment]
Not exactly bug. Moved item is taken out of the context so it's losing its index. It could be easily fixed tho.

**Comment by badtant** [comment]
Would be great since i'm using the index to render the item

**Comment by tajo** [comment]
Fix was merged. Will be released soon.

**Comment by badtant** [comment]
any news on releasing this? would be great :)

**Comment by tajo** [comment]
Published as `2.0.2`
