### ISSUE TITLE
Nested sortable table with drag handle: dragging children table row moves parent table row

### ISSUE THREAD

**Issue by yann-combarnous** [tajo/react-movable#83]
Have not had a chance to create a Sandbox yet, but just reporting in case there is a trivial workaround.

I have a use case of having a table with sortable rows, which each row containing another table with sortable row. I am using drag handle (data-movable-handle).

In this case, I see the issue that dragging one row from the nested table sometimes drags the parent row from the parent table. Would there be an easy workaround for fixing this? 

Maybe providing the ability to customize the "data-movable-handle" property name so there is no conflict between the 2 components?

**Comment by ido-journey** [comment]
having the same issue using a simple nested mapped list.

**Comment by tajo** [comment]
Please add repro with https://stackblitz.com/edit/react-movable?file=src%2FApp.tsx
