### ISSUE TITLE
Unable to forbid certain item to move at certain index

### ISSUE THREAD

**Issue by vtarelkin** [tajo/react-movable#90]
@tajo hi and thank you for your library! 
I wonder are there any options in onChange handler to forbid to move certain item to certain position (for example at the start of the list) ? Cannot get the value of the dragged element.

**Comment by vtarelkin** [comment]
this library definitely need some customizing on dragged item. 

something like

    beforeDrag?: (params: BeforeDragParams) => void;

```
export interface BeforeDragParams {
    elements: Element[];
    oldIndex: number;
    plannedIndex: number;
}
```

**Comment by tajo** [comment]
There is no support for this.
