### ISSUE TITLE
Autoscrolling is not working inside material ui drawer component.

### ISSUE THREAD

**Issue by nathan755** [tajo/react-movable#96]
Should the autoscrolling just work out of the box? Im having an issue where its not working whenever I'm using it within a Drawer component from material ui. 

Working example:
![working-example](https://github.com/tajo/react-movable/assets/50217607/f9a6d724-cd30-4ea1-8d2d-6f186fc09bac)

Example within a Drawer component from mui
![draw-example](https://github.com/tajo/react-movable/assets/50217607/27dd2ce0-b59d-490d-94fb-34e4379581ed)

[Codesandbox of issue](https://codesandbox.io/s/fragrant-bush-yln65z) example of the issue

Does anyone have any ideas.

**Comment by tajo** [comment]
There's been some auto-scrolling improvements landed, please test the latest version.
